services:
  db:
    image: postgres:15
    container_name: e-commerce-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_DB: ${DB_NAME:-websitebanhangmini}
    mem_limit: 512m # Đã giảm xuống 512m để nhường chỗ cho .NET SQL Server
    cpus: 0.5
    ports:
      - "6000:5432"
    volumes:
      - pgdata_ecommerce:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: e-commerce-redis
    restart: always
    mem_limit: 128m # Giới hạn cứng 128MB RAM
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379" # Có thể ẩn đi nếu chỉ gọi nội bộ

  api:
    build:
      context: ../../be
      dockerfile: Dockerfile
    container_name: e-commerce-web
    restart: unless-stopped
    mem_limit: 350m # Giới hạn RAM cho Node.js API
    ports:
      - "8888:8888"
    env_file:
      - ../../be/.env
    environment:
      # Ghi đè các biến cần thiết cho môi trường production container
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_SSL: false
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata_ecommerce:
    name: e-commrcemini_pgdata_ecommerce
